--- Makefile.original	2024-10-24 20:45:15
+++ Makefile	2024-10-24 20:45:37
@@ -93,7 +93,7 @@
 
 # Constants
 ALL_PLATFORMS = linux/amd64 linux/arm64 windows/amd64/ltsc2022 windows/amd64/ltsc2019 darwin/amd64
-DEFAULT_REGISTRY = docker.io/netapp
+DEFAULT_REGISTRY = ghcr.io/postfinance
 TRIDENT_CONFIG_PKG = github.com/netapp/trident/config
 OPERATOR_CONFIG_PKG = github.com/netapp/trident/operator/config
 TRIDENT_KUBERNETES_PKG = github.com/netapp/trident/persistent_store/crd
